export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const SAVE_SHIPPING_DETAILS = 'SAVE_SHIPPING_DETAILS';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export const CART_EMPTY = 'CART_EMPTY';